### ISSUE TITLE
Token with 'kid' not existing in JWKS raises KeyError exception

### ISSUE THREAD

**Issue by pgs-fhonckiewicz** [artsalliancemedia/thunderstorm-auth-library#16]
https://github.com/artsalliancemedia/thunderstorm-auth-library/blob/0bd36b51dcce2aee5636fd78d9681a82823bcd2b/thunderstorm_auth/decoder.py#L29

For malicious token containing key_id not existing in JWKS KeyError exception is raised. Please catch this type of error and reraise exception derived from thunderstorm_auth.exceptions.TokenError class.

**Comment by will-norris** [comment]
Fixed by https://github.com/artsalliancemedia/thunderstorm-auth-library/pull/17
