### ISSUE TITLE
Algorithm should be get from JWKS

### ISSUE THREAD

**Issue by pgs-fhonckiewicz** [artsalliancemedia/thunderstorm-auth-library#18]
https://github.com/artsalliancemedia/thunderstorm-auth-library/blob/0bd36b51dcce2aee5636fd78d9681a82823bcd2b/thunderstorm_auth/decoder.py#L35

Having valid JWKS using RS256 algorithm and valid token raises "jwt.exceptions.InvalidAlgorithmError: The specified alg value is not allowed" because algorithm is set as fixed string instead of taken from JWKS itself.

Example public key:
```json
{
  "kty": "RSA",
  "e": "AQAB",
  "use": "enc",
  "kid": "1",
  "alg": "RS256",
  "n": "glDIRAF5CeZTPQhGzZYBLOfGJaCNDz-8sTe4PkUkZw6wewewuF4CglOxJ1AnC5X-WkbEgWymOZREzoVW5PZftsXVu-WO-JLUZYWKCTP0XA_ti7jrwA_xdKefQ-iEocvfsCehozY9lvOaU5AwXOqf-EWtRAmyWmRVQlK3qMJ4uZVbiDIzkAAmsirV8duyWLsDOvvt3I8qewlAPs6xBorgoBw3uXBDdbr_mLmkNkSAs0E46TuWcVAiCtZF0C0qHJHtg3DMzdELFbGOIg6DnACJkm2QLbbk09xvF45uuItW8TTEatisnJpxA0M2WGCWi8QnMT2AmfcFJfdhLXK8zr_opQ"
}
```

**Comment by will-norris** [comment]
Since tokens are provided by the user service, and the user service only encrypts tokens using the RS512 I think this is the correct response. i.e. users would never be generating their own tokens using alternative algorithms.

**Comment by pgs-fhonckiewicz** [comment]
Getting algorithm from JWKS would be more flexible as JWKS are self-defining. Currently switching to a different algorithm would require updating library and rebuilding all services that depends on the lib. This can be avoided in a future releases by simple change like: `algorithms=jwks['keys'][key_id]['alg']`. So it would be nice enhancement allowing library client to decide which algorithm will be used.

**Comment by will-norris** [comment]
Fair point, I'll add a ticket for this and do some work on it when I have some free time :+1:

**Comment by will-norris** [comment]
Fixed in: https://github.com/artsalliancemedia/thunderstorm-auth-library/pull/19
