### ISSUE TITLE
Not catching jwt.exceptions.DecodeError

### ISSUE THREAD

**Issue by pgs-fhonckiewicz** [artsalliancemedia/thunderstorm-auth-library#22]
In the commit: da6c17e47c85198ac513fddf08c2f296b7c5a984 implementing getting algorithm from JWKS, some changes result in stop catching jwt.exceptions.DecodeError which causes a regression for example when valid token is signed with invalid key. Please revert catching jwt.exceptions.DecodeError in  thunderstorm_auth/decoder.py file.

**Comment by will-norris** [comment]
Hey sorry this was caused by my fix, provided you haven't started work on this already I'm happy to fix

**Comment by pgs-fhonckiewicz** [comment]
No problem, I haven't started work on in yet

**Comment by will-norris** [comment]
Fixed in: https://github.com/artsalliancemedia/thunderstorm-auth-library/pull/23
